backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: 'src/data/assets'
public_folder: 'static/assets'

collections:
  - label: "Landing"
    name: "pages"
    folder: "src/data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "headding", widget: "string"}   
      - {label: "Description", name: "description", widget: "string"} 
  
  - label: "Markdown"
    name: "markdown"
    files:
      - file: "src/data/banner.md"
        label: "Banner"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Description2", name: "boxdescription", widget: "string"}
          - {label: "Typing Letters", name: "bannertyping", widget: "list", fields: [{label: "name", name: "name", widget: "string"}, {label: "Letter Count", name: "count", widget: "string"}]}
      - file: "src/data/status.md"
        label: "Status"
        name: "status"
        fields:
          - {label: Status, name: "Status", widget: "list", fields: [{ label: statusnumber, name: "statusnumber", widget: "string" }, { label: statustitle, name: "statustitle", widget: "string" }, { label: statusimage, name: "statusimage", widget: "image" }]}
      - file: "src/data/about.md"
        label: "about"
        name: "About"
        fields:
          - {label: "abouttitle", name: "abouttitle", widget: "string"}
          - {label: "aboutImg", name: "aboutImg", widget: "image"}
      - file: "src/data/blogs.md"
        label: "Blogs"
        name: "blogs"
        fields:
          - {label: "Title", name: "blogtitle", widget: "string"}
          - {label: "Blog Container", name: "blogs", widget: "list", fields: [{label: "Title", name: "blogcardtitle", widget: "string"}, {label: "Description", name: "blogcarddesc", widget: "string"}, {label: "date", name: "blogcarddate", widget: "string"}, {label: "image", name: "blogimg", widget: "image"}]}
      - file: "src/data/clints.md"
        label: "Clints"
        name: "clints"
        fields:
          - {label: "Title", name: "clintstitle", widget: "string"}
          - {label: "Clints Container", name: "clints", widget: "list", fields: [{label: "Title", name: "carousaltitle", widget: "string"}, {label: "Review", name: "carousalreview", widget: "string"}, {label: "Name", name: "clintname", widget: "string"},  {label: "Designation", name: "clintdesignation", widget: "string"}, {label: "Profile Image", name: "clintimg", widget: "image"}]}
      - file: "src/data/online.md"
        label: "Online"
        name: "online"
        fields:
          - {label: "Title", name: "onlinetitle", widget: "string"}
          - {label: "Description", name: "onlinedesc", widget: "string"}
          - {label: "Image", name: "onlineimg", widget: "image"}
      - file: "src/data/patners.md"
        label: "Patners"
        name: "patners"
        fields:
          - {label: "Title", name: "Patnertitle", widget: "string"}
          - {label: "Description", name: "patnerdescription", widget: "string"}
          - {label: "Patner carousal", name: "patnercarousal", widget: "list", fields: [{label: "Patner Container", name: "patners", widget: "list", fields: [{label: "Image", name: "patnerimage", widget: "image"}]} ]}
      - file: "src/data/Standout.md"
        label: "Standout"
        name: "standout"
        fields:
          - {label: "Title", name: "Patnertitle", widget: "string"}
          - {label: "Description", name: "patnerdescription", widget: "string"}
          - {label: "StandOut Container", name: "standout", widget: "list", fields: [{label: "Title", name: "head", widget: "string"}, {label: "Description", name: "content", widget: "sring"}, {label: "Standout cards", name: "Standoutcontainer", widget: "list", fields: [{label: "Name", name: "standname", widget: "sring"}, {label: "Image", name: "standimage", widget: "image"}]} ]}
      - file: "src/data/team.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Teams Container", name: "teams", widget: "list", fields: [{label: "Title", name: "teamtitle", widget: "string"}, {label: "Team cards", name: "team", widget: "list", fields: [{label: "Name", name: "teaamname", widget: "sring"}, {label: "Designation", name: "teamdesignation", widget: "string"}, {label: "Image", name: "teamimg", widget: "image"}]} ]}
      - file: "src/data/wedo.md"
        label: "Wedo"
        name: "wedo"
        fields:
          - {label: "Title", name: "wedotitle", widget: "string"}
          - {label: "Wedo container", name: "patnercarousal", widget: "list", fields: [{label: "Name", name: "wedoname", widget: "string"}, {label: "Description", name: "wedodesc", widget: "string"}, {label: "Image", name: "wedoimg", widget: "image"}]}
  - label: "Formulations"
    name: "formulation"
    files:
      - file: "src/data/Formulations/fbanner.md"
        label: "Banner"
        name: "fbanner"
        fields:
          - {label: "Title", name: "description", widget: "string"}
      - file: "src/data/Formulations/casestudy.md"
        label: "Casestudy"
        name: "casestudy"
        fields:
          - {label: "Casestudy", name: "Casestudy", widget: "list", fields: [{label: "Title", name: "Casestudytitle", widget: "string"}, {label: "Casestudycards", name: "Casestudycards", widget: "list", fields: [{label: "Title", name: "Casestudyblockid", widget: "string"}, {label: "Description", name: "Casestudyname", widget: "string"}, {label: "Date", name: "Casestudydesc", widget: "string"}, {label: "Image", name: "image", widget: "image"}]}]}
      - file: "src/data/Formulations/ffacility.md"
        label: "Facility"
        name: "ffacility"
        fields:
          - {label: "Facility", name: "Ffacility", widget: "list", fields: [{label: "Title", name: "Ffacilitytitle", widget: "string"}, {label: "Description", name: "Ffacilitydis", widget: "string"}, {label: "Facility Cards", name: "Ffacilitycards", widget: "list", fields: [{label: "Id", name: "Ffacilityblockid", widget: "string"}, {label: "Title", name: "Ffacilityname", widget: "string"}, {label: "Description", name: "Ffacilitydesc", widget: "string"}, {label: "Image", name: "ffacilitypic", widget: "image"}]}]}
      - file: "src/data/Formulations/fservices.md"
        label: "Services"
        name: "fservices"
        fields:
          - {label: "Services", name: "fservices", widget: "list", fields: [{label: "Title", name: "fservicetitle", widget: "string"}, {label: "Description", name: "fservicedesc", widget: "string"}, {label: "Services Cards", name: "fservicecards", widget: "list", fields: [{label: "Id", name: "fservicecardid", widget: "string"}, {label: "Title", name: "fservicecardtitle", widget: "string"}, {label: "Description", name: "fservicecarddesc", widget: "string"}, {label: "Main title", name: "fserviceminicardsmaintitle", widget: "string"}, {label: "Image", name: "fservicepic", widget: "image"}, {label: Mini Blocks, name: "fserviceminicards", widget: "list", fields: [{label: "fserviceminicardstitle", name: "fserviceminicardstitle", widget: "string"}, {label: "Images", name: "fserviceminicardsimg", widget: "image"}]}]}]}
  - label: "Manfacturing"
    name: "manfacturing"
    files:
      - file: "src/data/Manfacturing/mbanner.md"
        label: "Banner"
        name: "mbanner"
        fields:
          - {label: "Title", name: "description", widget: "string"}
      - file: "src/data/Manfacturing/capabilities.md"
        label: "Capabilities"
        name: "capable"
        fields:
          - {label: "Capabilities", name: "Capabilities", widget: "list", fields: [{label: "Title", name: "capabilitiestitle", widget: "string"}, {label: "Description", name: "capabilitiesdesc", widget: "string"}, {label: "Capabilities Cards", name: "capabilitiescards", widget: "list", fields: [{label: "Id", name: "capabilitiescardid", widget: "string"}, {label: "Title", name: "capabilitiescardtitle", widget: "string"}, {label: "Description", name: "capabilitiescarddesc", widget: "string"}, {label: "Image", name: "image", widget: "image"}, {label: "Mini Blocks", name: "capabilitiesminicards", widget: "list", fields: [{label: "Title", name: "capabilitiesminicardstitle", widget: "string"}, {label: "Image", name: "image", widget: "image"}]}]}]}
      - file: "src/data/Manfacturing/facility.md"
        label: "Facility"
        name: "facility"
        fields:
          - {label: "Facility", name: "Facility", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Facility Cards", name: "Facilitycards", widget: "list", fields: [{label: "Id", name: "facilityid", widget: "string"}, {label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Description2", name: "description2", widget: "string"}, {label: "Description3", name: "description3", widget: "string"}, {label: "Image", name: "fimage", widget: "image"}]}]}
      - file: "src/data/Manfacturing/industry.md"
        label: "Industry"
        name: "industry"
        fields:
          - {label: "Industry", name: "industry", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Industry Cards", name: "industrycards", widget: "list", fields: [{label: "Id", name: "industryid", widget: "string"}, {label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Image", name: "Image", widget: "image"}]}]}
      - file: "src/data/Manfacturing/quality.md"
        label: "Quality"
        name: "quality"
        fields:
          - {label: "Quality", name: "Quality", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Description1", name: "description1", widget: "string"}, {label: "Description2", name: "description2", widget: "string"}, {label: "Image", name: "image", widget: "image"} ]}
      - file: "src/data/Manfacturing/qualityassurance.md"
        label: "Quality Assurance"
        name: "qualityassurance"
        fields:
          - {label: "Quality Assurance", name: "qualityassurance", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "QA Container", name: "qualityassuranceminicontainer", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Image", name: "image", widget: "image"}]}]}
  - label: "Digital"
    name: "Digital"
    files:
      - file: "src/data/Digital/dbanner.md"
        label: "Banner"
        name: "dbanner"
        fields:
          - {label: "Title", name: "description", widget: "string"}
      - file: "src/data/Digital/dsolution.md"
        label: "Solution"
        name: "dsolution"
        fields:
          - {label: "Solution", name: "dsolution", widget: "list", fields: [{label: "Title", name: "dsolutiontitle", widget: "string"}, {label: "Description", name: "dsolutiondesc", widget: "string"}, {label: "Cards", name: "dsolutioncards", widget: "list", fields: [{label: "Id", name: "dsolutioncardid", widget: "string"}, {label: "Title", name: "dsolutioncardtitle", widget: "string"}, {label: "Description", name: "dsolutioncarddesc", widget: "string"}, {label: "Title1", name: "dsolutionminicardsmaintitle", widget: "string"}, {label: "Title2", name: "dsolutionminicardsmaintitle", widget: "string"}, {label: "Image", name: "Image", widget: "image"}, {label: "Mini cards", name: "dsolutionminicards", widget: "list", fields: [{label: "Title", name: "dsolutionminicardstitle", widget: "string"}, {label: "Description", name: "dsolutionminicardstitle2", widget: "string"}, {label: "Image", name: "dsolutionminicardsimg", widget: "image"}]}]}]}
      - file: "src/data/Manfacturing/productdev.md"
        label: "Product Development"
        name: "productdev"
        fields:
          - {label: "Product Development", name: "prodev", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Description", name: "description", widget: "string"}, {label: "Product Container", name: "prodevminicontainer", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "Image", name: "Image", widget: "image"}]}]}