backend:
  name: git-gateway
  branch: main

media_folder: src/data/assets
public_folder: /assets

collections:
  - name: "Status"
    label: "status"
    folder: "src/pages/Home"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Status",
          name: "Status",
          widget: "list",
          fields:
            [
              { label: statusnumber, name: "statusnumber", widget: "string" },
              { label: statustitle, name: "statustitle", widget: "string" },
              { label: statusimage, name: "statusimage", widget: "image" },
            ],
        }
