backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: 'src/data/assets'
public_folder: 'src/data/assets'

collections:
  - label: "Landing"
    name: "pages"
    folder: "src/data"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "headding", widget: "string"}   
      - {label: "Description", name: "description", widget: "string"} 
  
  - label: "Markdown"
    name: "markdown"
    files:
      - file: "src/data/Status.md"
        label: "status"
        name: "Status"
        fields:
          - {label: Status, name: "Status", widget: "list", fields: [{ label: statusnumber, name: "statusnumber", widget: "string" }, { label: statustitle, name: "statustitle", widget: "string" }, { label: statusimage, name: "statusimage", widget: "image" }]}
          
              
              